version: '2.2'
networks:
  pce-env:
    external: true
    name: pce-env
services:
  seafile:
    build:
      context: .docker
      dockerfile: seafile/Dockerfile
    image: '${DOCKER_DEVBOX_REGISTRY}${DOCKER_DEVBOX_REGISTRY_REPOSITORY}/seafile'
    user: '${USER_ID}:${GROUP_ID}'
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
    networks:
      - default
      - pce-env
    volumes:
      - 'seafile-ccnet:/seafile/ccnet'
      - 'seafile-seafile-data:/seafile/seafile-data'
      - 'seafile-seahub-data:/seafile/seahub-data'
      - '${COMPOSE_PROJECT_DIR}/seafile/conf:/seafile/conf'
    environment:
      - 'SEAFILE_URL=https://seafile.${DOCKER_DEVBOX_DOMAIN_PREFIX}.${DOCKER_DEVBOX_DOMAIN}'
      - 'MYSQL_HOST=seafile-db.${COMPOSE_NETWORK_NAME}'
      - 'MYSQL_USER=seafile'
      - 'MYSQL_USER_PASSWD=seafile'
      - 'MYSQL_ROOT_PASSWD=reciacloud'
      - 'ADMIN_EMAIL=admin@example.com'
      - 'ADMIN_PASSWORD=admin'
  seafile-db:
    build:
      context: .docker
      dockerfile: seafile-db/Dockerfile
    image: '${DOCKER_DEVBOX_REGISTRY}${DOCKER_DEVBOX_REGISTRY_REPOSITORY}/seafile-db'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
    environment:
      - 'MYSQL_ROOT_PASSWORD=reciacloud'
    volumes:
      - '${COMPOSE_PROJECT_DIR}:/workdir'
      - 'seafile-db:/var/lib/mysql'
  onlyoffice:
    build:
      context: .docker
      dockerfile: onlyoffice/Dockerfile
    image: '${DOCKER_DEVBOX_REGISTRY}${DOCKER_DEVBOX_REGISTRY_REPOSITORY}/onlyoffice'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
volumes:  
  seafile-seafile-data: null
  seafile-seahub-data: null
  seafile-ccnet: null
  seafile-db: null