version: '2.2'
networks:
  default:
    external: true
    name: recia-env
services:
  ldap:
    build:
      context: .docker
      dockerfile: ldap/Dockerfile
    image: '${DOCKER_DEVBOX_REGISTRY}recia-env/ldap'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
    environment:
      - 'LDAP_BACKEND=bdb'
      - 'LDAP_DOMAIN=esco-centre.fr'
      - 'LDAP_BASE_DN=dc=esco-centre,dc=fr'
    volumes:
      - '${COMPOSE_PROJECT_DIR}:/workdir'
      - 'ldap-data:/var/lib/ldap'
      - 'ldap-config:/etc/ldap/slapd.d'
  cas:
    build:
      context: .docker
      dockerfile: cas/Dockerfile
    image: '${DOCKER_DEVBOX_REGISTRY}recia-env/cas'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
    depends_on:
      - ldap
volumes:
  ldap-data: null
  ldap-config: null
