version: '2.2'
networks:
  recia-env:
    external: true
    name: recia-env
services:
  nextcloud:
    build:
      context: .docker
      dockerfile: nextcloud/Dockerfile
    image: '${DOCKER_DEVBOX_REGISTRY}reciacloud/nextcloud'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
    networks:
      - default
      - recia-env
    volumes:
      - '${COMPOSE_PROJECT_DIR}/nextcloud-config:/var/www/html/config'
      - 'nextcloud-custom-apps:/var/www/html/custom_apps'
      - '${COMPOSE_PROJECT_DIR}/../nextcloud-custom-apps/nextcloud-recia-custom:/var/www/html/custom_apps/reciacustom'
      - 'nextcloud-data:/var/www/html/data'
      - 'nextcloud-themes:/var/www/html/themes'
  nextcloud-db:
    build:
      context: .docker
      dockerfile: nextcloud-db/Dockerfile
    image: '${DOCKER_DEVBOX_REGISTRY}reciacloud/nextcloud-db'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=reciacloud'
    volumes:
      - '${COMPOSE_PROJECT_DIR}:/workdir'
      - 'nextcloud-db:/var/lib/postgresql/data'
  onlyoffice:
    build:
      context: .docker
      dockerfile: onlyoffice/Dockerfile
    image: '${DOCKER_DEVBOX_REGISTRY}reciacloud/onlyoffice'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
volumes:
  nextcloud-custom-apps:
  nextcloud-data:
  nextcloud-themes:
  nextcloud-db:
