version: '2.2'
services:
  nextcloud-php:
    environment:
      - 'XDEBUG_CONFIG=idekey=reciacloud remote_host=${HOST_IP}'
      - 'PHP_IDE_CONFIG=serverName=reciacloud'
#    scale: 5
  nextcloud:
    environment:
      - 'VIRTUAL_HOST=nextcloud.${DOCKER_DEVBOX_DOMAIN_PREFIX}.${DOCKER_DEVBOX_DOMAIN},nextcloud.1d.${DOCKER_DEVBOX_DOMAIN_PREFIX}.${DOCKER_DEVBOX_DOMAIN},nextcloud.2d.${DOCKER_DEVBOX_DOMAIN_PREFIX}.${DOCKER_DEVBOX_DOMAIN}'
      - 'VIRTUAL_PORT=80'
    labels:
      - traefik.enable=true
      - 'traefik.frontend.rule=Host:nextcloud.${DOCKER_DEVBOX_DOMAIN_PREFIX}.${DOCKER_DEVBOX_DOMAIN},nextcloud.1d.${DOCKER_DEVBOX_DOMAIN_PREFIX}.${DOCKER_DEVBOX_DOMAIN},nextcloud.2d.${DOCKER_DEVBOX_DOMAIN_PREFIX}.${DOCKER_DEVBOX_DOMAIN}'
      - traefik.port=80
      - traefik.frontend.redirect.regexp=https://(.*):?.*
      - traefik.frontend.redirect.replacement=https://$$1
    networks:
      - default
      - reverse-proxy
#    scale: 5
  nextcloud-db:
    ports:
      - '${DOCKER_DEVBOX_PORT_PREFIX}32:5432'
  onlyoffice:
    environment:
      - 'VIRTUAL_HOST=onlyoffice.${DOCKER_DEVBOX_DOMAIN_PREFIX}.${DOCKER_DEVBOX_DOMAIN}'
      - 'VIRTUAL_PORT=80'
    labels:
      - traefik.enable=true
      - 'traefik.frontend.rule=Host:onlyoffice.${DOCKER_DEVBOX_DOMAIN_PREFIX}.${DOCKER_DEVBOX_DOMAIN}'
      - traefik.port=80
      - traefik.frontend.redirect.regexp=https://(.*):?.*
      - traefik.frontend.redirect.replacement=https://$$1
    networks:
      - default
      - reverse-proxy
networks:
  reverse-proxy:
    name: '${DOCKER_DEVBOX_REVERSE_PROXY_NETWORK}'
    external: true
