version: '2.2'
services:
  mkdocs:
    environment:
      - 'VIRTUAL_HOST=${DOCKER_DEVBOX_DOMAIN_PREFIX}.${DOCKER_DEVBOX_DOMAIN}'
      - 'VIRTUAL_PORT=8000'
    labels:
      - traefik.enable=true
      - 'traefik.frontend.rule=Host:${DOCKER_DEVBOX_DOMAIN_PREFIX}.${DOCKER_DEVBOX_DOMAIN}'
      - traefik.port=8000
      - traefik.frontend.redirect.regexp=https://(.*):?.*
      - traefik.frontend.redirect.replacement=https://$$1
    networks:
      - default
      - reverse-proxy
networks:
  reverse-proxy:
    name: '${DOCKER_DEVBOX_REVERSE_PROXY_NETWORK}'
    external: true
