version: '2.2'
services:
  nextcloud-php:
    image: '${DOCKER_DEVBOX_REGISTRY}reciacloud/nextcloud-php'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
    volumes:
      - '${COMPOSE_PROJECT_DIR}/nextcloud:/var/www/html'
      - '${COMPOSE_PROJECT_DIR}/config:/config'
      - '${COMPOSE_PROJECT_DIR}/patches:/patches'
      - '${COMPOSE_PROJECT_DIR}/../nextcloud-custom-apps/nextcloud-recia-custom:/var/www/html/custom_apps/reciacustom'
      - 'nextcloud-data:/var/www/html/data'
  nextcloud:
    image: '${DOCKER_DEVBOX_REGISTRY}reciacloud/nextcloud'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
    volumes:
      - '${COMPOSE_PROJECT_DIR}/nextcloud:/var/www/html'
      - '${COMPOSE_PROJECT_DIR}/config:/config'
      - '${COMPOSE_PROJECT_DIR}/patches:/patches'
      - '${COMPOSE_PROJECT_DIR}/../nextcloud-custom-apps/nextcloud-recia-custom:/var/www/html/custom_apps/reciacustom'
      - 'nextcloud-data:/var/www/html/data'
      - '${COMPOSE_PROJECT_DIR}/.docker/nextcloud/nginx.conf:/etc/nginx/nginx.conf'
  nextcloud-db:
    image: '${DOCKER_DEVBOX_REGISTRY}reciacloud/nextcloud-db'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
    command: -c 'shared_buffers=256MB' -c 'max_connections=1024'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=reciacloud'
    volumes:
      - '${COMPOSE_PROJECT_DIR}:/workdir'
      - 'nextcloud-db:/var/lib/postgresql/data'
  onlyoffice:
    image: '${DOCKER_DEVBOX_REGISTRY}reciacloud/onlyoffice'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
  clamav:
    image: mk0x/docker-clamav:alpine
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
  ldap:
    image: '${DOCKER_DEVBOX_REGISTRY}pce-env/ldap'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
    environment:
      - 'LDAP_BACKEND=bdb'
      - 'LDAP_DOMAIN=esco-centre.fr'
      - 'LDAP_BASE_DN=dc=esco-centre,dc=fr'
    volumes:
      - '${COMPOSE_PROJECT_DIR}:/workdir'
      - 'ldap-data:/var/lib/ldap'
      - 'ldap-config:/etc/ldap/slapd.d'
volumes:
  nextcloud:
  nextcloud-data:
  nextcloud-db:
  ldap-data:
  ldap-config:
