version: '2.2'
services:
  ldap:
    ports:
      - "${DOCKER_DEVBOX_PORT_PREFIX}39:389"
      - "${DOCKER_DEVBOX_PORT_PREFIX}69:636"
    command: '--loglevel debug'
  cas:
    ports:
      - "${DOCKER_DEVBOX_PORT_PREFIX}80:8080"
      - "${DOCKER_DEVBOX_PORT_PREFIX}43:8443"
    # - "${DOCKER_DEVBOX_PORT_PREFIX}05:5005"
    #command: "./gradlew remoteDebug" # Use remote debug task to enable CAS remote debug on tcp/5005
    networks:
      - default
      - reverse-proxy
    environment:
      - 'VIRTUAL_HOST=cas.${DOCKER_DEVBOX_DOMAIN_PREFIX}.${DOCKER_DEVBOX_DOMAIN}'
      - 'VIRTUAL_PORT=8080'
    labels:
      - traefik.enable=true
      - 'traefik.frontend.rule=Host:cas.${DOCKER_DEVBOX_DOMAIN_PREFIX}.${DOCKER_DEVBOX_DOMAIN}'
      - traefik.port=8080
      - traefik.frontend.redirect.regexp=https://(.*):?.*
      - traefik.frontend.redirect.replacement=https://$$1
networks:
  reverse-proxy:
    name: '${DOCKER_DEVBOX_REVERSE_PROXY_NETWORK}'
    external: true
