version: '2.2'
networks:
  default:
    external: true
    name: pce-env
services:
  ldap:
    build:
      context: .docker
      dockerfile: ldap/Dockerfile
    image: '${DOCKER_DEVBOX_REGISTRY}${DOCKER_DEVBOX_REGISTRY_REPOSITORY}/ldap'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
    environment:
      - 'LDAP_BACKEND=bdb'
      - 'LDAP_DOMAIN=esco-centre.fr'
      - 'LDAP_BASE_DN=dc=esco-centre,dc=fr'
    volumes:
      - '${COMPOSE_PROJECT_DIR}:/workdir'
      - 'ldap-data:/var/lib/ldap'
      - 'ldap-config:/etc/ldap/slapd.d'
  cas:
    build:
      context: .docker
      dockerfile: cas/Dockerfile
    image: '${DOCKER_DEVBOX_REGISTRY}${DOCKER_DEVBOX_REGISTRY_REPOSITORY}/cas'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
    depends_on:
      - ldap
    volumes:
      - '${COMPOSE_PROJECT_DIR}/cas-services:/etc/cas/services'
      - '${COMPOSE_PROJECT_DIR}/cas-keystore/thekeystore:/etc/cas/thekeystore'
      - '${COMPOSE_PROJECT_DIR}/cas-saml:/etc/cas/saml'
      - '${COMPOSE_PROJECT_DIR}/cas/config/cas.properties:/etc/cas/cas.properties'
volumes:
  ldap-data: null
  ldap-config: null
