version: '2.2'
networks:
  pce-env:
    external: true
    name: pce-env
services:
  nextcloud-php:
    build:
      context: .docker
      dockerfile: nextcloud-php/Dockerfile
    image: '${DOCKER_DEVBOX_REGISTRY}${DOCKER_DEVBOX_REGISTRY_REPOSITORY}/nextcloud-php'
    user: '${USER_ID}:${GROUP_ID}'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
    networks:
      - default
      - pce-env
    volumes:
      - '${COMPOSE_PROJECT_DIR}/nextcloud:/var/www/html'
      - '${COMPOSE_PROJECT_DIR}/config:/config'
      - '${COMPOSE_PROJECT_DIR}/patches:/patches'
      - '${COMPOSE_PROJECT_DIR}/../nextcloud-custom-apps/nextcloud-recia-custom:/var/www/html/custom_apps/reciacustom'
      - '${COMPOSE_PROJECT_DIR}/.docker/nextcloud-php/config/custom-php.ini:/usr/local/etc/php/conf.d/config-php.ini:ro'
  nextcloud:
    build:
      context: .docker
      dockerfile: nextcloud/Dockerfile
    image: '${DOCKER_DEVBOX_REGISTRY}${DOCKER_DEVBOX_REGISTRY_REPOSITORY}/nextcloud'
    user: '${USER_ID}:${GROUP_ID}'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
    volumes:
      - '${COMPOSE_PROJECT_DIR}/nextcloud:/var/www/html'
      - '${COMPOSE_PROJECT_DIR}/config:/config'
      - '${COMPOSE_PROJECT_DIR}/patches:/patches'
      - '${COMPOSE_PROJECT_DIR}/../nextcloud-custom-apps/nextcloud-recia-custom:/var/www/html/custom_apps/reciacustom'
      - '${COMPOSE_PROJECT_DIR}/.docker/nextcloud/nginx.conf:/etc/nginx/nginx.conf'
  nextcloud-db:
    build:
      context: .docker
      dockerfile: nextcloud-db/Dockerfile
    image: '${DOCKER_DEVBOX_REGISTRY}${DOCKER_DEVBOX_REGISTRY_REPOSITORY}/nextcloud-db'
    user: '${USER_ID}:${GROUP_ID}'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=reciacloud'
    command: -c 'shared_buffers=256MB' -c 'max_connections=1024'
    volumes:
      - '${COMPOSE_PROJECT_DIR}:/workdir'
      - 'nextcloud-db:/var/lib/postgresql/data'
  collabora:
    build:
      context: .docker
      dockerfile: collabora/Dockerfile
    image: '${DOCKER_DEVBOX_REGISTRY}reciacloud/collabora'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
    cap_add:
      - MKNOD
    environment:
      - 'DONT_GEN_SSL_CERT=1'
      - 'domain=nextcloud\\.${DOCKER_DEVBOX_DOMAIN_PREFIX}\\.${DOCKER_DEVBOX_DOMAIN}'
      - 'username=admin'
      - 'password=S3cRet'
      - 'extra_params=--o:ssl.enable=false --o:ssl.termination=true'
  clamav:
    image: mk0x/docker-clamav:alpine
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
volumes:
  nextcloud-db:
