version: '2.2'
networks:
  recia-env:
    external: true
    name: recia-env
services:
  seafile:
    build:
      context: .docker
      dockerfile: seafile/Dockerfile
    image: '${DOCKER_DEVBOX_REGISTRY}reciacloud/seafile'
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
    networks:
      - default
      - recia-env
    volumes:
      - 'seafile-ccnet:/seafile/ccnet'
      - 'seafile-seafile-data:/seafile/seafile-data'
      - 'seafile-seahub-data:/seafile/seahub-data'
      - '${COMPOSE_PROJECT_DIR}/volumes/seafile-conf:/seafile/conf'
    environment:
      - 'SEAFILE_URL=https://seafile.${DOCKER_DEVBOX_DOMAIN_PREFIX}.${DOCKER_DEVBOX_DOMAIN}'
      - 'MYSQL_HOST=seafile-db.${COMPOSE_NETWORK_NAME}'
      - 'MYSQL_USER=seafile'
      - 'MYSQL_USER_PASSWD=seafile'
      - 'MYSQL_ROOT_PASSWD=reciacloud'
      - 'ADMIN_EMAIL=admin@example.com'
      - 'ADMIN_PASSWORD=admin'
  seafile-db:
    build:
      context: .docker
      dockerfile: seafile-db/Dockerfile
    image: '${DOCKER_DEVBOX_REGISTRY}reciacloud/seafile-db'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
    environment:
      - 'MYSQL_ROOT_PASSWORD=reciacloud'
    volumes:
      - '${COMPOSE_PROJECT_DIR}:/workdir'
      - 'seafile-db:/var/lib/mysql'
  collabora:
    build:
      context: .docker
      dockerfile: collabora/Dockerfile
    image: '${DOCKER_DEVBOX_REGISTRY}reciacloud/collabora'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
    cap_add:
      - MKNOD
    environment:
      - 'DONT_GEN_SSL_CERT=1'
      - 'domain=seafile\\.${DOCKER_DEVBOX_DOMAIN_PREFIX}\\.${DOCKER_DEVBOX_DOMAIN}'
      - 'username=admin'
      - 'password=S3cRet'
      - 'extra_params=--o:ssl.enable=false --o:ssl.termination=true'
volumes:  
  seafile-seafile-data: null
  seafile-seahub-data: null
  seafile-ccnet: null
  seafile-db: null