#!/usr/bin/env bash
. "$DOCKER_DEVBOX_SCRIPTS_PATH/.bash.lib.d/50-docker"

run --workdir="$(_docker_workdir "/workdir")" nextcloud-db psql --dbname=postgres://reciacloud:reciacloud@nextcloud-db/reciacloud "$@"
