#!/usr/bin/env bash
. "$DOCKER_DEVBOX_DIR/.bash.lib.d/50-docker"

run --user postgres --workdir="$(_docker_workdir "/workdir")" nextcloud-db psql --dbname=postgres://reciacloud:reciacloud@nextcloud-db/reciacloud "$@"
