version: '2.2'
services:
  nextcloud:
    build:
      context: .docker
      dockerfile: nextcloud/Dockerfile
    image: '${DOCKER_DEVBOX_REGISTRY}reciacloud/nextcloud'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
    volumes:
      - '${COMPOSE_PROJECT_DIR}/volumes/nextcloud/config:/var/www/html/config'
      - '${COMPOSE_PROJECT_DIR}/volumes/nextcloud/custom_apps:/var/www/html/custom_apps'
      - '${COMPOSE_PROJECT_DIR}/volumes/nextcloud/data:/var/www/html/data'
      - '${COMPOSE_PROJECT_DIR}/volumes/nextcloud/themes/recia:/var/www/html/themes/recia'
  nextcloud-db:
    build:
      context: .docker
      dockerfile: nextcloud-db/Dockerfile
    image: '${DOCKER_DEVBOX_REGISTRY}reciacloud/nextcloud-db'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=reciacloud'
    volumes:
      - '${COMPOSE_PROJECT_DIR}:/workdir'
      - 'nextcloud-db-data:/var/lib/postgresql/data'
  collabora:
    build:
      context: .docker
      dockerfile: collabora/Dockerfile
    image: '${DOCKER_DEVBOX_REGISTRY}reciacloud/collabora'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
    cap_add:
      - MKNOD
    environment:
      - 'DONT_GEN_SSL_CERT=1'
      - 'domain=nextcloud\\.${DOCKER_DEVBOX_DOMAIN_PREFIX}\\.${DOCKER_DEVBOX_DOMAIN}'
      - 'username=admin'
      - 'password=S3cRet'
      - 'extra_params=--o:ssl.enable=false --o:ssl.termination=true'
volumes:
  nextcloud-db-data:
